name: Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: uv python install
    - name: Ruff
      run: |
      uv run check rapidchecker
      uv run ruff format --check rapidchecker
    - name: Mypy
      run: |
      uv run mypy rapidchecker
      uv run ruff format --check
    - name: Pytest
      run: uv run pytest tests
